# Generated by Django 2.1.7 on 2019-04-12 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giftcard',
            fields=[
                ('barcode', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed', models.BooleanField(verbose_name='Is the card redeemed?')),
                ('created', models.DateTimeField(verbose_name='Date of creation')),
                ('activated', models.DateTimeField(verbose_name='Activated on')),
                ('validity', models.DateTimeField(verbose_name='Valid until')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('profile_type', models.CharField(default='Participant', max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcards.Profile'),
        ),
    ]
