# Generated by Django 2.1.7 on 2019-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0002_auto_20190412_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pensionentity',
            name='email',
        ),
    ]
