# Generated by Django 2.1.7 on 2019-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0004_remove_participant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='validity',
            field=models.DateTimeField(null=True, verbose_name='Valid until'),
        ),
    ]
