# Generated by Django 2.1.7 on 2019-04-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcards', '0005_auto_20190412_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
