# Generated by Django 2.1.7 on 2019-04-13 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PensionFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsn', models.CharField(max_length=100)),
                ('fund_name', models.CharField(choices=[('abp', 'ABP fund'), ('pfzw', 'PFZW Fund'), ('sf', 'Some Fund'), ('gf', 'Gold Fund')], default='abp', max_length=5)),
                ('active', models.BooleanField(default=False)),
                ('ascription', models.CharField(max_length=100, null=True)),
                ('eligible', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fulltime_salary', models.FloatField(default=0.0)),
                ('entitlements', models.CharField(max_length=1000)),
                ('participant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockdigid.Participant')),
            ],
        ),
    ]
