# Generated by Django 2.1.7 on 2019-04-13 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensionfund',
            name='id',
        ),
        migrations.AddField(
            model_name='pensionfund',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
