# Generated by Django 2.1.7 on 2019-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionFund',
            fields=[
                ('bsn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('ascription', models.CharField(max_length=100, null=True)),
                ('eligible', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('fulltime_salary', models.FloatField(default=0.0)),
                ('entitlements', models.CharField(max_length=1000)),
            ],
        ),
    ]
