# Generated by Django 2.1.7 on 2019-04-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0002_auto_20190413_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionfund',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockdigid.Participant'),
        ),
    ]
