# Generated by Django 2.1.7 on 2019-04-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0002_pensionfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionfund',
            name='participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockdigid.Participant'),
        ),
        migrations.AlterField(
            model_name='pensionfund',
            name='fund_name',
            field=models.CharField(choices=[('abp', 'ABP fund'), ('pfzw', 'PFZW Fund'), ('sf', 'Some Fund'), ('gf', 'Gold Fund')], default='abp', max_length=5),
        ),
    ]
