# Generated by Django 2.1.7 on 2019-04-13 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0003_auto_20190413_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionfund',
            name='session_id',
            field=models.CharField(default=datetime.datetime(2019, 4, 13, 10, 27, 33, 616132, tzinfo=utc), max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pensionfund',
            name='bsn',
            field=models.CharField(max_length=100),
        ),
    ]
