# Generated by Django 2.1.7 on 2019-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0003_auto_20190413_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensionfund',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
