# Generated by Django 2.1.7 on 2019-04-13 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mockdigid', '0004_auto_20190413_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensionfund',
            name='session_id',
        ),
        migrations.AddField(
            model_name='pensionfund',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2019, 4, 13, 10, 31, 45, 931164, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
